import type { Metadata } from 'next';
import { Header } from '@/components/header/header';
import { ThemeProvider } from '@/providers/theme-provider/theme-context';
import { ReduxProvider } from '@/providers/redux-provider/redux-provider';
import { ModalProvider } from '@/providers/modal-provider/modal-provider';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <ReduxProvider>
            <ModalProvider>
              <Header />
              {children}
            </ModalProvider>
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
